$pip3 uninstall tensorflow
$pip3 uninstall tensorflow_gpu

$pip3 uninstall tensorflow
$pip3 uninstall tensorflow_gpu



$ pip3 install tensorflow-gpu --user



raceback (most recent call last):
  File "/usr/local/lib/python3.7/shutil.py", line 563, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/estimator_ckpt_converter' -> '/tmp/pip-uninstall-h6vq7sog/estimator_ckpt_converter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/uninstall.py", line 75, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 817, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 360, in remove
    moved.stash(path)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_uninstall.py", line 257, in stash
    renames(path, new_path)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 303, in renames
    shutil.move(old, new)
  File "/usr/local/lib/python3.7/shutil.py", line 578, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/estimator_ckpt_converter'
s_wigglesworth@cloudshell:~ (cool-monolith-280109)$ pip3 uninstall tensorflow_gpu
Skipping tensorflow-gpu as it is not installed.
s_wigglesworth@cloudshell:~ (cool-monolith-280109)$ pip3